name: flutter_is_emulator
description: Plugin to detect whether the current device is an emulator or simulator
version: 1.0.0
author: Edouard Marquez <moi@edouard-marquez.me>
homepage: https://github.com/g123k/flutter_is_emulator

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.2.0"
  
dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: fr.g123k.flutterisemulator
    pluginClass: FlutterIsEmulatorPlugin
